##################################################################################################
# greeter-client services
##################################################################################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: greeter-client
  namespace: greetings
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: greetings
  labels:
    app: frontend
    service: frontend
    app.kubernetes.io/name: greeter-client
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 7007
      targetPort: 7007
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-client
  namespace: greetings
  labels:
    app: greeter-client
    app.kubernetes.io/name: greeter-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      restartPolicy: Always
      shareProcessNamespace: true
      securityContext: {}
      serviceAccountName: greeter-client
      terminationGracePeriodSeconds: 0
      containers:
        - name: frontend
          image: greeter_client:local
          ports:
            - containerPort: 7007
              name: http
        - name: frontend-go-instrumentation
          image: otel-go-agent:v0.6
          env:
            - name: OTEL_TARGET_EXE
              value: /app/gclient
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: otel-collector:4317
            - name: OTEL_SERVICE_NAME
              value: greeter_client
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"
          securityContext:
            runAsUser: 0
            capabilities:
              add:
                - SYS_PTRACE
            privileged: true
          volumeMounts:
            - mountPath: /sys/kernel/debug
              name: kernel-debug
      volumes:
        - name: kernel-debug
          hostPath:
            path: /sys/kernel/debug
